version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
      # CircleCI PostgreSQL images available at: https://circleci.com/developer/images/image/cimg/postgres
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: counters

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Get dependencies
          command: |
            npm install

      #  Wait for Postgres to be ready before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run unit tests
          environment: # environment variables for the database url and path to migration files
            CONTACTS_DB_URL: "postgresql://root:secret@localhost:5432/counters?sslmode=disable"
          command: |
            make migrateup
            make test | tee ${TEST_RESULTS}/test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
