version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
        environment:
          DATABASE_URL: "postgresql://root:secret@localhost:5432/counters?sslmode=disable"
      # CircleCI PostgreSQL images available at: https://circleci.com/developer/images/image/cimg/postgres
      - image: postgres:12
        environment:
          PGHOST: localhost
          PGUSER: root
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: counters
          POSTGRES_HOST_AUTH_METHOD: trust

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Get dependencies
          command: |
            npm install

      #  Wait for Postgres to be ready before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run unit tests
          environment: # environment variables for the database url and path to migration files
            CONTACTS_DB_URL: "postgresql://root:secret@localhost:5432/counters?sslmode=disable"
          command: |
            SELECT datname FROM pg_catalog.pg_database;
            psql -h localhost -U root -d counters -f create_table.sql
            make test | tee ${TEST_RESULTS}/test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  main:
    jobs:
      - build
    